### ISSUE TITLE
Empty view collections resources

### ISSUE THREAD

**Issue by Spheerys** [modxcms/Collections#176]
I'm running :
- MODX 2.4.2
- Collections 3.3.0

I have an empty view view I try to view collections resources :

![bug-collections](https://cloud.githubusercontent.com/assets/2228364/11375747/308e8b18-92dd-11e5-8d00-1c7b07edaaf4.png)

I can go in "Add-on" > "Collections views" without problem.
In the MODX log, I have nothing, and Apache2 log are not saying anything about 403 error :(

What could be the reason of this "blank screen of the death" ?

**Comment by theboxer** [comment]
Do you have any view in Collection views? If not, create one and set it as global. (In fresh installs it sometimes happens that you don't get default view, it should be fixed in next version)

**Comment by Spheerys** [comment]
yes the Blog view is defined and set as global (in fact, the translated term is "default" = "par défaut" in french)

Here my JS console debug :
![bug-collections](https://cloud.githubusercontent.com/assets/2228364/11377506/76ec5b0e-92e6-11e5-800f-28116f07219e.png)

**Comment by theboxer** [comment]
Did you change anything in the view?

**Comment by Spheerys** [comment]
Yes I did. I add 2 columns : longtitle and menuindex (with hidden parameter)
Save and want to try if it's works : result blank view !
And before it was working well.

I tried to remove the 2 columns added but the blank view is still present

**Comment by theboxer** [comment]
I'm not sure, if it was working before changes, than it must be something wrong set in your view.

**Comment by Spheerys** [comment]
I have deleted the Blog view (set by default) and create a new one : I don't have the blank screen of the death !
But I didn't retreive the children resources of my doc ID 6 !
If I set the ID6 to Resource type, I have all children as classical resources.
But how can I retreive them as "blog entry" inside the Collection view ?

**Comment by Spheerys** [comment]
I solved my problem with using a daily backup... 
It's look like Collection addon seams to be... sensitive... :)
